<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("1С-Битрикс: Управление сайтом");
?>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
<h1>sdfgsf</h1>
Пустая страница. <a href="/bitrix/admin/">Перейти в Панель &nbsp;Управления</a>


<br>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>